# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(550, 700)
        MainWindow.setMinimumSize(QtCore.QSize(550, 700))
        MainWindow.setMaximumSize(QtCore.QSize(550, 700))
        MainWindow.setSizeIncrement(QtCore.QSize(505, 700))
        MainWindow.setStyleSheet("\n"
"*{\n"
"    background-color:#555555;\n"
"    font: 11pt \"Century Gothic\";\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    border-radius:15%;\n"
"    background-color:#F0EE6E;\n"
"    font-size:15px;\n"
"    font-weight:500;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:black;\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color:white;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  border: 1px solid grey;\n"
"  background: white;\n"
"  selection-background-color: blue;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(210, 540, 141, 41))
        self.searchButton.setStyleSheet("")
        self.searchButton.setObjectName("searchButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 50, 211, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.actorBox = QtWidgets.QComboBox(self.centralwidget)
        self.actorBox.setGeometry(QtCore.QRect(150, 280, 261, 31))
        self.actorBox.setObjectName("actorBox")
        self.directorBox = QtWidgets.QComboBox(self.centralwidget)
        self.directorBox.setGeometry(QtCore.QRect(150, 370, 261, 31))
        self.directorBox.setObjectName("directorBox")
        self.genreBox = QtWidgets.QComboBox(self.centralwidget)
        self.genreBox.setGeometry(QtCore.QRect(150, 460, 261, 31))
        self.genreBox.setObjectName("genreBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 250, 121, 16))
        self.label_2.setStyleSheet("color:#F0EE6E;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 340, 121, 16))
        self.label_3.setStyleSheet("color:#F0EE6E;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 430, 121, 16))
        self.label_4.setStyleSheet("color:#F0EE6E;")
        self.label_4.setObjectName("label_4")
        self.restrictBox = QtWidgets.QComboBox(self.centralwidget)
        self.restrictBox.setGeometry(QtCore.QRect(150, 190, 261, 31))
        self.restrictBox.setObjectName("restrictBox")
        self.restrictBox.addItem("")
        self.restrictBox.addItem("")
        self.restrictBox.addItem("")
        self.restrictBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 150, 81, 21))
        self.label_5.setStyleSheet("color:#F0EE6E;")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MovieFinder"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Actor:"))
        self.label_3.setText(_translate("MainWindow", "Director:"))
        self.label_4.setText(_translate("MainWindow", "Genre:"))
        self.restrictBox.setItemText(0, _translate("MainWindow", "Actor"))
        self.restrictBox.setItemText(1, _translate("MainWindow", "Director"))
        self.restrictBox.setItemText(2, _translate("MainWindow", "Genre"))
        self.restrictBox.setItemText(3, _translate("MainWindow", "All categories"))
        self.label_5.setText(_translate("MainWindow", "Search by:"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
